# Generated by Django 5.2.5 on 2025-09-15 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_subscription"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
