# Generated by Django 5.2.5 on 2025-09-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_delete_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(max_length=450, verbose_name="Способ оплаты"),
        ),
    ]
