# Generated by Django 5.2.5 on 2025-09-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0004_alter_lesson_course"),
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="lms.course",
                verbose_name="Оплаченный курс",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment",
                to="lms.lesson",
                verbose_name="Оплаченный урок",
            ),
        ),
    ]
