# Generated by Django 5.2.5 on 2025-09-11 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_payment_paid_course_alter_payment_paid_lesson"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
