# Generated by Django 5.2.5 on 2025-09-15 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_delete_payment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
