# Generated by Django 5.2.5 on 2025-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lms/course/images/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="lms/lesson/images/",
                verbose_name="Превью",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(
                blank=True, max_length=150, null=True, verbose_name="Ссылка на видео"
            ),
        ),
    ]
