# Generated by Django 5.2.5 on 2025-09-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0005_course_owner_lesson_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_link",
            field=models.URLField(max_length=150, verbose_name="Ссылка на видео"),
        ),
    ]
